name: Raindrop Feeds Push
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      # 步骤1 拉取仓库代码
      - uses: actions/checkout@v3
      # 步骤2 给当前服务器安装node
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm install
      - name: push message
        run: pnpm run tsx ./src/raindrop.ts --webhook=${{ secrets.DINGDINGBOT_WEBHOOK }} --secret=${{ secrets.DINGDINGBOT_SECRET }} --raindropToken=${{ secrets.RAINDROP_TOKEN }}
